import { z } from 'zod';

import { objectIdSchema } from '../category/category.schema';

export const idParamSchema = z.object({ id: objectIdSchema });

/** The reveal token is 16 base64url characters, generated by the model. */
export const tokenParamSchema = z.object({
  token: z.string().regex(/^[A-Za-z0-9_-]{10,64}$/, 'invalid token'),
});

const boolish = z
  .string()
  .optional()
  .transform((value) => value === 'true');

const dateOnly = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, 'must be YYYY-MM-DD')
  .optional();

export const listBoltiQuerySchema = z.object({
  q: z.string().trim().min(1).optional(),
  status: z.enum(['draft', 'ready', 'qr_failed']).optional(),
  isRevealed: boolish,
  from: dateOnly,
  to: dateOnly,
  page: z.string().optional(),
  limit: z.string().optional(),
  sort: z.string().optional(),
});

export const qrQuerySchema = z.object({
  format: z.enum(['png', 'svg']).optional(),
  size: z.string().optional(),
});

/** Bulk print run. Capped because each code costs real CPU. */
export const bulkQrSchema = z.object({
  ids: z.array(objectIdSchema).min(1, 'select at least one').max(200, 'at most 200 at a time'),
});

export type ListBoltiQuery = z.infer<typeof listBoltiQuerySchema>;
export type QrQuery = z.infer<typeof qrQuerySchema>;
export type BulkQrInput = z.infer<typeof bulkQrSchema>;
